#!/usr/bin/env python3
"""Fábio chat bridge: App/WhatsApp queue -> Hermes -> Supabase/UAZAPI.

Small sidecar intentionally kept outside Hermes core:
- HTTP endpoint ingests UAZAPI messages into public.fabio_chat_mensagens.
- Poller consumes role='professor' AND fabio_seen_at IS NULL.
- Response is generated by the local Fabio/Hermes oneshot runner.
- Response is inserted back as role='fabio' with the same channel.
- WhatsApp channel additionally sends POST /send/text when UAZAPI token is configured.
"""
from __future__ import annotations

import argparse
import concurrent.futures
import json
import os
import re
import subprocess
import sys
import threading
import time
import unicodedata
from datetime import datetime, timezone, timedelta
from zoneinfo import ZoneInfo
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Dict, Optional
from urllib.parse import urlparse

import requests

HERMES_HOME = Path(os.getenv("HERMES_HOME", "/home/fabio/.hermes"))
ENV_FILE = HERMES_HOME / ".env"
ROOT_DIR = Path(os.getenv("FABIO_HOME", "/home/fabio"))
HERMES_CMD = os.getenv("FABIO_HERMES_CMD", "/home/fabio/.hermes/hermes-agent/venv/bin/python -m hermes_cli.main")
CHAT_SKILLS = os.getenv("FABIO_CHAT_SKILLS", "chat-fabio-la-music").strip()
POLL_INTERVAL = float(os.getenv("FABIO_CHAT_POLL_INTERVAL", "3"))
MESSAGE_DEBOUNCE_SECONDS = float(os.getenv("FABIO_CHAT_DEBOUNCE_SECONDS", "5"))
MESSAGE_BATCH_LIMIT = int(os.getenv("FABIO_CHAT_BATCH_LIMIT", "8"))
CONTEXT_CACHE_TTL = float(os.getenv("FABIO_CONTEXT_CACHE_TTL", "90"))
HERMES_MODE = os.getenv("FABIO_HERMES_MODE", "api").strip().lower()
HERMES_API_URL = os.getenv("FABIO_HERMES_API_URL", "http://127.0.0.1:8644/v1/chat/completions").strip()
HERMES_API_KEY = os.getenv("FABIO_HERMES_API_KEY") or os.getenv("API_SERVER_KEY") or ""
HERMES_API_MODEL = os.getenv("FABIO_HERMES_API_MODEL", os.getenv("API_SERVER_MODEL_NAME", "fabio")).strip()
HERMES_API_TIMEOUT = float(os.getenv("FABIO_HERMES_API_TIMEOUT", "75"))
HERMES_API_FALLBACK_ONESHOT = os.getenv("FABIO_HERMES_API_FALLBACK_ONESHOT", "true").strip().lower() not in {"0", "false", "no", "off"}
_CONTEXT_CACHE: dict[tuple[int, str], tuple[float, Dict[str, Any]]] = {}
PORT = int(os.getenv("FABIO_CHAT_BRIDGE_PORT", "8645"))
BRIDGE_SECRET = os.getenv("FABIO_CHAT_BRIDGE_SECRET", "")
SUPABASE_URL = (os.getenv("LAREPORT_SUPABASE_URL") or "https://ouqwbbermlzqqvtqwlul.supabase.co").rstrip("/")
SUPABASE_KEY = os.getenv("LAREPORT_SUPABASE_SERVICE_ROLE") or os.getenv("SUPABASE_SERVICE_ROLE_KEY") or ""
UAZAPI_URL = (os.getenv("FABIO_UAZAPI_URL") or os.getenv("UAZAPI_URL") or "https://lamusic.uazapi.com").rstrip("/")
UAZAPI_TOKEN = os.getenv("FABIO_UAZAPI_TOKEN") or os.getenv("UAZAPI_TOKEN") or ""
LOG_PATH = Path(os.getenv("FABIO_CHAT_BRIDGE_LOG", "/home/fabio/.hermes/logs/fabio-chat-bridge.log"))

_HTTP_TIMEOUT = (10, 60)


def _load_env_file(path: Path = ENV_FILE) -> None:
    if not path.exists():
        return
    for line in path.read_text(errors="ignore").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        if line.startswith("export "):
            line = line[len("export "):]
        key, val = line.split("=", 1)
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        os.environ.setdefault(key, val)


def log(msg: str, **fields: Any) -> None:
    LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    safe = {k: v for k, v in fields.items() if k not in {"token", "secret", "authorization"}}
    line = json.dumps({"ts": datetime.now(timezone.utc).isoformat(), "msg": msg, **safe}, ensure_ascii=False)
    print(line, flush=True)
    with LOG_PATH.open("a", encoding="utf-8") as f:
        f.write(line + "\n")


def now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def sb_headers(prefer: Optional[str] = None) -> Dict[str, str]:
    if not SUPABASE_KEY:
        raise RuntimeError("LAREPORT_SUPABASE_SERVICE_ROLE missing")
    h = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json",
    }
    if prefer:
        h["Prefer"] = prefer
    return h


def sb_get(path: str, params: Dict[str, str]) -> Any:
    r = requests.get(f"{SUPABASE_URL}{path}", headers=sb_headers(), params=params, timeout=_HTTP_TIMEOUT)
    if r.status_code >= 400:
        raise RuntimeError(f"Supabase GET {path} {r.status_code}: {r.text[:500]}")
    return r.json()


def sb_post(path: str, body: Any, prefer: Optional[str] = None) -> requests.Response:
    return requests.post(f"{SUPABASE_URL}{path}", headers=sb_headers(prefer), json=body, timeout=_HTTP_TIMEOUT)


def sb_patch(path: str, params: Dict[str, str], body: Any, prefer: Optional[str] = None) -> requests.Response:
    return requests.patch(f"{SUPABASE_URL}{path}", headers=sb_headers(prefer), params=params, json=body, timeout=_HTTP_TIMEOUT)


def get_data(body: Dict[str, Any]) -> Dict[str, Any]:
    if isinstance(body.get("messages"), list) and body["messages"]:
        return body["messages"][0] or {}
    if isinstance(body.get("message"), dict):
        return body["message"]
    if isinstance(body.get("data"), dict):
        return body["data"]
    return body


def extract_text(body: Dict[str, Any]) -> Optional[str]:
    data = get_data(body)
    value = data.get("content") or data.get("text") or data.get("body") or data.get("caption")
    if isinstance(value, dict):
        value = value.get("text") or value.get("body")
    if value is None:
        return None
    value = str(value).strip()
    return value or None


def extract_phone(body: Dict[str, Any]) -> Optional[str]:
    data = get_data(body)
    raw = data.get("chatid") or data.get("sender") or data.get("from") or data.get("remoteJid") or ""
    if "@lid" in str(raw):
        raw = body.get("chat", {}).get("wa_chatid") or raw
    phone = str(raw).split("@")[0]
    digits = re.sub(r"\D+", "", phone)
    return digits or None


def extract_message_id(body: Dict[str, Any]) -> Optional[str]:
    data = get_data(body)
    for key in ("id", "messageId", "message_id", "wa_message_id", "keyId"):
        value = data.get(key) or body.get(key)
        if value:
            return str(value)
    key = data.get("key")
    if isinstance(key, dict):
        for k in ("id", "messageId"):
            if key.get(k):
                return str(key[k])
    return None


def is_ignorable_uazapi(body: Dict[str, Any]) -> bool:
    event = body.get("EventType") or body.get("event_type") or body.get("type") or body.get("event")
    if event and str(event) != "messages":
        return True
    data = get_data(body)
    if not data:
        return True
    if data.get("wasSentByApi") is True:
        return True
    if data.get("fromMe") is True:
        return True
    if data.get("isGroup") is True:
        return True
    return False


def resolve_identity_by_phone(phone: str) -> Dict[str, Any]:
    r = sb_post("/rest/v1/rpc/fabio_identidade_whatsapp", {"p_telefone": phone})
    if r.status_code >= 400:
        raise RuntimeError(f"fabio_identidade_whatsapp {r.status_code}: {r.text[:500]}")
    data = r.json()
    if not isinstance(data, dict) or not data.get("ok"):
        raise RuntimeError(f"identity_not_resolved: {data}")
    tipo = data.get("tipo")
    if tipo not in {"professor", "admin"}:
        raise RuntimeError(f"identity_tipo_invalid: {data}")
    return data


def resolve_professor_by_phone(phone: str) -> Dict[str, Any]:
    data = resolve_identity_by_phone(phone)
    if data.get("tipo") != "professor":
        raise RuntimeError(f"identity_is_not_professor: {data}")
    return data


def insert_identity_message(identity: Dict[str, Any], text: str, channel: str, wa_message_id: Optional[str] = None) -> Dict[str, Any]:
    tipo = identity.get("tipo") or "professor"
    row = {
        "identidade_tipo": tipo,
        "role": "professor",
        "kind": "text",
        "content": text,
        "channel": channel,
    }
    if tipo == "admin":
        row["usuario_id"] = int(identity["usuario_id"])
    else:
        row["professor_id"] = int(identity["professor_id"])
    if wa_message_id:
        row["wa_message_id"] = wa_message_id
    r = sb_post("/rest/v1/fabio_chat_mensagens", row, prefer="return=representation")
    if r.status_code == 409:
        return {"duplicate": True, "wa_message_id": wa_message_id}
    if r.status_code >= 400:
        raise RuntimeError(f"insert chat message {r.status_code}: {r.text[:500]}")
    data = r.json()
    return data[0] if isinstance(data, list) and data else row


def insert_professor_message(professor_id: int, text: str, channel: str, wa_message_id: Optional[str] = None) -> Dict[str, Any]:
    return insert_identity_message({"tipo": "professor", "professor_id": int(professor_id)}, text, channel, wa_message_id)


def claim_next_message() -> Optional[Dict[str, Any]]:
    select_cols = "id,identidade_tipo,usuario_id,professor_id,role,kind,content,media_extracted_text,channel,wa_message_id,criado_em,fabio_seen_at,fabio_done_at"
    rows = sb_get("/rest/v1/fabio_chat_mensagens", {
        "select": select_cols,
        "role": "eq.professor",
        "fabio_seen_at": "is.null",
        "order": "criado_em.asc",
        "limit": "1",
    })
    stale_claim = False
    if not rows:
        stale_seconds = int(os.getenv("FABIO_STALE_CLAIM_SECONDS", "180"))
        stale_max_age_seconds = int(os.getenv("FABIO_STALE_CLAIM_MAX_AGE_SECONDS", "900"))
        now_utc = datetime.now(timezone.utc)
        stale_before = (now_utc - timedelta(seconds=stale_seconds)).isoformat()
        stale_after = (now_utc - timedelta(seconds=stale_max_age_seconds)).isoformat()
        rows = sb_get("/rest/v1/fabio_chat_mensagens", {
            "select": select_cols,
            "role": "eq.professor",
            "fabio_done_at": "is.null",
            "fabio_seen_at": f"lt.{stale_before}",
            "criado_em": f"gte.{stale_after}",
            "order": "criado_em.asc",
            "limit": "1",
        })
        stale_claim = bool(rows)
    if not rows:
        return None
    row = rows[0]
    filters = {"id": f"eq.{row['id']}"}
    if not stale_claim:
        filters["fabio_seen_at"] = "is.null"
    r = sb_patch(
        "/rest/v1/fabio_chat_mensagens",
        filters,
        {"fabio_seen_at": now_iso()},
        prefer="return=representation",
    )
    if r.status_code >= 400:
        raise RuntimeError(f"claim message {r.status_code}: {r.text[:500]}")
    claimed = r.json()
    if not claimed:
        return None
    if stale_claim:
        log("stale_message_reclaimed", id=row.get("id"), professor_id=row.get("professor_id"), previous_seen_at=row.get("fabio_seen_at"))
    return claimed[0] if isinstance(claimed, list) and claimed else row


def _claim_specific_message(row: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    r = sb_patch(
        "/rest/v1/fabio_chat_mensagens",
        {"id": f"eq.{row['id']}", "fabio_seen_at": "is.null"},
        {"fabio_seen_at": now_iso()},
        prefer="return=representation",
    )
    if r.status_code >= 400:
        raise RuntimeError(f"claim specific message {r.status_code}: {r.text[:500]}")
    claimed = r.json()
    if not claimed:
        return None
    return claimed[0] if isinstance(claimed, list) and claimed else row


def collect_message_batch(first_row: Dict[str, Any]) -> list[Dict[str, Any]]:
    """Debounce bursty professor/admin chat and claim follow-up bubbles."""
    batch = [first_row]
    debounce_seconds = MESSAGE_DEBOUNCE_SECONDS
    if (first_row.get("channel") or "app") == "whatsapp":
        debounce_seconds = float(os.getenv("FABIO_CHAT_WHATSAPP_DEBOUNCE_SECONDS", "2"))
    if debounce_seconds > 0:
        time.sleep(debounce_seconds)
    filters = {
        "select": "id,identidade_tipo,usuario_id,professor_id,role,kind,content,media_extracted_text,channel,wa_message_id,criado_em",
        "role": "eq.professor",
        "fabio_seen_at": "is.null",
        "identidade_tipo": f"eq.{first_row.get('identidade_tipo') or 'professor'}",
        "channel": f"eq.{first_row.get('channel') or 'app'}",
        "criado_em": f"gte.{first_row.get('criado_em')}",
        "order": "criado_em.asc",
        "limit": str(max(0, MESSAGE_BATCH_LIMIT - 1)),
    }
    if (first_row.get("identidade_tipo") or "professor") == "admin":
        filters["usuario_id"] = f"eq.{int(first_row['usuario_id'])}"
    else:
        filters["professor_id"] = f"eq.{int(first_row['professor_id'])}"
    rows = sb_get("/rest/v1/fabio_chat_mensagens", filters)
    for row in rows or []:
        if row.get("id") == first_row.get("id"):
            continue
        claimed = _claim_specific_message(row)
        if claimed:
            batch.append(claimed)
    if len(batch) > 1:
        log("message_batch_collected", first_id=first_row.get("id"), count=len(batch), ids=[r.get("id") for r in batch])
    return batch


def merge_message_batch(batch: list[Dict[str, Any]]) -> Dict[str, Any]:
    if not batch:
        raise ValueError("empty message batch")
    if len(batch) == 1:
        return batch[0]
    merged = dict(batch[0])
    parts = []
    media_parts = []
    for row in batch:
        content = (row.get("content") or "").strip()
        media_text = (row.get("media_extracted_text") or "").strip()
        if content:
            parts.append(content)
        if media_text:
            media_parts.append(media_text)
    merged["content"] = "\n".join(parts).strip()
    merged["media_extracted_text"] = "\n".join(media_parts).strip() or None
    merged["_batch_ids"] = [str(r.get("id")) for r in batch]
    merged["_batch_count"] = len(batch)
    return merged


def mark_done(message_id: str) -> None:
    r = sb_patch("/rest/v1/fabio_chat_mensagens", {"id": f"eq.{message_id}"}, {"fabio_done_at": now_iso()})
    if r.status_code >= 400:
        log("mark_done_failed", status=r.status_code, body=r.text[:300])


def insert_fabio_response_for_row(source_row: Dict[str, Any], content: str, channel: str) -> Dict[str, Any]:
    tipo = source_row.get("identidade_tipo") or "professor"
    row = {
        "identidade_tipo": tipo,
        "role": "fabio",
        "kind": "text",
        "content": content,
        "channel": channel,
    }
    if tipo == "admin":
        row["usuario_id"] = int(source_row["usuario_id"])
    else:
        row["professor_id"] = int(source_row["professor_id"])
    r = sb_post("/rest/v1/fabio_chat_mensagens", row, prefer="return=representation")
    if r.status_code >= 400:
        raise RuntimeError(f"insert fabio response {r.status_code}: {r.text[:500]}")
    data = r.json()
    return data[0] if isinstance(data, list) and data else row


def insert_fabio_response(professor_id: int, content: str, channel: str) -> Dict[str, Any]:
    return insert_fabio_response_for_row({"identidade_tipo": "professor", "professor_id": int(professor_id)}, content, channel)


def canonical_phone(value: str) -> Optional[str]:
    digits = re.sub(r"\D+", "", value or "")
    if not digits:
        return None
    if digits.startswith("55"):
        return digits
    if len(digits) in (10, 11):
        return "55" + digits
    return digits


def professor_phone(professor_id: int) -> Optional[str]:
    rows = sb_get("/rest/v1/professores", {
        "select": "telefone_whatsapp",
        "id": f"eq.{int(professor_id)}",
        "limit": "1",
    })
    if not rows:
        return None
    return canonical_phone(rows[0].get("telefone_whatsapp") or "")


def recent_history(professor_id: int, limit: int = 10) -> list[Dict[str, Any]]:
    rows = sb_get("/rest/v1/fabio_chat_mensagens", {
        "select": "role,content,channel,criado_em",
        "professor_id": f"eq.{int(professor_id)}",
        "order": "criado_em.desc",
        "limit": str(limit),
    })
    return list(reversed(rows or []))


def today_brt() -> str:
    return datetime.now(ZoneInfo("America/Sao_Paulo")).date().isoformat()


def professor_context(professor_id: int, data: Optional[str] = None) -> Dict[str, Any]:
    """Fetch identity/agenda/context for the already-resolved professor.

    Cached for a short TTL: enough to make quick chat fluid, short enough not
    to hide schedule/context changes for long.
    """
    pid = int(professor_id)
    day = data or today_brt()
    key = (pid, day)
    now = time.time()
    cached = _CONTEXT_CACHE.get(key)
    if cached and now - cached[0] <= CONTEXT_CACHE_TTL:
        return cached[1]
    body = {"p_professor_id": pid, "p_data": day}
    r = sb_post("/rest/v1/rpc/fabio_contexto_professor", body)
    if r.status_code >= 400:
        raise RuntimeError(f"fabio_contexto_professor {r.status_code}: {r.text[:500]}")
    data_json = r.json()
    ctx = data_json if isinstance(data_json, dict) else {"ok": False, "raw": data_json}
    if ctx.get("ok"):
        _CONTEXT_CACHE[key] = (now, ctx)
    return ctx


def admin_context(usuario_id: int) -> Dict[str, Any]:
    r = sb_post("/rest/v1/rpc/fabio_contexto_admin", {"p_usuario_id": int(usuario_id)})
    if r.status_code >= 400:
        raise RuntimeError(f"fabio_contexto_admin {r.status_code}: {r.text[:500]}")
    data_json = r.json()
    return data_json if isinstance(data_json, dict) else {"ok": False, "raw": data_json}


def admin_phone(usuario_id: int) -> Optional[str]:
    rows = sb_get("/rest/v1/usuarios", {
        "select": "telefone",
        "id": f"eq.{int(usuario_id)}",
        "limit": "1",
    })
    if not rows:
        return None
    return canonical_phone(rows[0].get("telefone") or "")


def recent_history_for_row(row: Dict[str, Any], limit: int = 10) -> list[Dict[str, Any]]:
    tipo = row.get("identidade_tipo") or "professor"
    filters = {
        "select": "role,content,channel,criado_em,identidade_tipo,usuario_id,professor_id",
        "identidade_tipo": f"eq.{tipo}",
        "order": "criado_em.desc",
        "limit": str(limit),
    }
    if tipo == "admin":
        filters["usuario_id"] = f"eq.{int(row['usuario_id'])}"
    else:
        filters["professor_id"] = f"eq.{int(row['professor_id'])}"
    rows = sb_get("/rest/v1/fabio_chat_mensagens", filters)
    return list(reversed(rows or []))


def compact_professor_context(ctx: Dict[str, Any]) -> str:
    try:
        return json.dumps(ctx, ensure_ascii=False, separators=(",", ":"))[:10000]
    except Exception:
        return str(ctx)[:4000]


def _norm_text(value: Any) -> str:
    raw = str(value or "").lower()
    raw = "".join(c for c in unicodedata.normalize("NFKD", raw) if not unicodedata.combining(c))
    return re.sub(r"\s+", " ", raw).strip()


def _course_base(value: Any) -> str:
    text = _norm_text(value)
    # Emusys often adds technical suffixes such as "Canto T" or "Piano IND".
    text = re.sub(r"\b(t|ind|kids|adulto|adultos)\b", "", text)
    return re.sub(r"\s+", " ", text).strip()


def _has_pedagogical_history_intent(current_text: str, hist: list[Dict[str, Any]]) -> bool:
    recent = "\n".join((h.get("content") or "") for h in hist[-6:])
    hay = _norm_text(current_text + "\n" + recent)
    patterns = [
        "ultima aula", "ultimo conteudo", "conteudo da ultima", "relembrar",
        "o que foi feito", "o que ela fez", "o que ele fez", "trabalhou",
        "prontuario", "historico", "continuidade", "aula passada", "ultima vez",
    ]
    return any(p in hay for p in patterns)


def _fetch_professor_roster(professor_id: int) -> list[Dict[str, Any]]:
    rows = sb_get("/rest/v1/vw_fabio_carteira_professor", {
        "select": "aluno_id,aluno_nome,curso_nome,professor_id,professor_nome,unidade_nome",
        "professor_id": f"eq.{int(professor_id)}",
        "order": "aluno_nome.asc",
        "limit": "500",
    })
    return rows or []


def _resolve_student_course_from_chat(professor_id: int, current_text: str, hist: list[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    roster = _fetch_professor_roster(professor_id)
    if not roster:
        return None

    # Resolve student primarily from PROFESSOR messages. Fábio's own agenda
    # response lists many students; if we use it blindly, the resolver can pick
    # the last listed student (ex.: Davi) instead of the one asked (ex.: Luiza).
    professor_recent = "\n".join((h.get("content") or "") for h in hist[-8:] if h.get("role") == "professor")
    all_recent = "\n".join((h.get("content") or "") for h in hist[-8:])
    professor_hay = _norm_text(professor_recent + "\n" + current_text)
    all_hay = _norm_text(all_recent + "\n" + current_text)
    current_norm = _norm_text(current_text)

    def score_students(hay: str, base_score: int) -> dict[str, tuple[int, Dict[str, Any]]]:
        scores: dict[str, tuple[int, Dict[str, Any]]] = {}
        for row in roster:
            name = row.get("aluno_nome") or ""
            n = _norm_text(name)
            if not n:
                continue
            parts = [part for part in n.split() if len(part) >= 3]
            first = parts[0] if parts else ""
            score = 0
            if n and n in hay:
                score = base_score + 100 + hay.rfind(n)
            elif first and re.search(rf"\b{re.escape(first)}\b", hay):
                score = base_score + 50 + hay.rfind(first)
            if score and (n not in scores or score > scores[n][0]):
                scores[n] = (score, row)
        return scores

    student_scores = score_students(professor_hay, 10000)
    if not student_scores:
        student_scores = score_students(all_hay, 0)
    if not student_scores:
        return None

    selected_student = sorted(student_scores.values(), key=lambda x: x[0], reverse=True)[0][1]
    selected_name = selected_student.get("aluno_nome")
    same_student_rows = [r for r in roster if _norm_text(r.get("aluno_nome")) == _norm_text(selected_name)]

    # Course resolution: current message wins ("a de canto"), then professor
    # messages, then all context.
    def course_match_score(row: Dict[str, Any]) -> int:
        base = _course_base(row.get("curso_nome"))
        if not base:
            return 0
        if re.search(rf"\b{re.escape(base)}\b", current_norm):
            return 300
        if re.search(rf"\b{re.escape(base)}\b", professor_hay):
            return 200
        if re.search(rf"\b{re.escape(base)}\b", all_hay):
            return 100
        return 0

    if len(same_student_rows) == 1:
        return same_student_rows[0]
    scored = [(course_match_score(r), r) for r in same_student_rows]
    scored = [x for x in scored if x[0] > 0]
    if scored:
        return sorted(scored, key=lambda x: x[0], reverse=True)[0][1]
    return selected_student

def _latest_chronological_class(professor_id: int, aluno_id: int, course_name: str) -> Optional[Dict[str, Any]]:
    rows = sb_get("/rest/v1/vw_fabio_aulas_contexto", {
        "select": "aula_local_id,data_aula,data_hora_inicio,horario_inicio_brt,curso_nome,aluno_id,aluno_nome,professor_id,professor_nome,presenca_status,cancelada,anotacoes,anotacoes_fabio",
        "professor_id": f"eq.{int(professor_id)}",
        "aluno_id": f"eq.{int(aluno_id)}",
        "data_aula": f"lt.{today_brt()}",
        "order": "data_aula.desc,data_hora_inicio.desc,aula_local_id.desc",
        "limit": "30",
    })
    base = _course_base(course_name)
    seen: set[Any] = set()
    for row in rows or []:
        if base and base not in _course_base(row.get("curso_nome")):
            continue
        key = row.get("aula_local_id") or (row.get("data_aula"), row.get("curso_nome"))
        if key in seen:
            continue
        seen.add(key)
        texto = (row.get("anotacoes_fabio") or row.get("anotacoes") or "").strip()
        return {
            "data": row.get("data_aula"),
            "hora": str(row.get("horario_inicio_brt") or row.get("data_hora_inicio") or "")[:8],
            "curso": row.get("curso_nome"),
            "aula_id": row.get("aula_local_id"),
            "presenca": row.get("presenca_status"),
            "cancelada": row.get("cancelada"),
            "tem_registro": bool(texto),
            "texto_preview": texto[:1200],
        }
    return None


def _latest_registered_content(professor_id: int, aluno_id: int, course_name: str) -> Optional[Dict[str, Any]]:
    r = sb_post("/rest/v1/rpc/fabio_prontuario_aluno", {
        "p_aluno_id": int(aluno_id),
        "p_professor_id": int(professor_id),
        "p_limite": 30,
    })
    if r.status_code >= 400:
        raise RuntimeError(f"fabio_prontuario_aluno {r.status_code}: {r.text[:500]}")
    data = r.json()
    timeline = data.get("linha_do_tempo") if isinstance(data, dict) else []
    base = _course_base(course_name)
    seen: set[tuple[Any, Any, str]] = set()
    for item in timeline or []:
        texto = (item.get("texto") or "").strip()
        if not texto:
            continue
        if base and base not in _course_base(item.get("curso")):
            continue
        key = (item.get("data"), item.get("curso"), texto[:80])
        if key in seen:
            continue
        seen.add(key)
        return {
            "data": item.get("data"),
            "curso": item.get("curso"),
            "origem": item.get("origem"),
            "presenca": item.get("presenca"),
            "professor": item.get("professor"),
            "nr_da_aula": item.get("nr_da_aula"),
            "texto": texto[:1800],
        }
    return None


def pedagogical_prefetch(professor_id: int, current_text: str, hist: list[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    if not _has_pedagogical_history_intent(current_text, hist):
        return None
    resolved = _resolve_student_course_from_chat(professor_id, current_text, hist)
    if not resolved:
        return {"intent": "historico_pedagogico", "resolved": None, "erro": "aluno/curso não resolvido pelo contexto recente"}
    aluno_id = int(resolved["aluno_id"])
    course = resolved.get("curso_nome") or ""
    latest_class = _latest_chronological_class(professor_id, aluno_id, course)
    latest_content = _latest_registered_content(professor_id, aluno_id, course)
    return {
        "intent": "historico_pedagogico",
        "resolved": {
            "aluno_id": aluno_id,
            "aluno_nome": resolved.get("aluno_nome"),
            "curso_nome": course,
            "professor_id": professor_id,
        },
        "ultima_aula_cronologica": latest_class,
        "ultimo_registro_com_conteudo": latest_content,
    }


def compact_pedagogical_context(ctx: Optional[Dict[str, Any]]) -> str:
    if not ctx:
        return "(não acionado)"
    try:
        return json.dumps(ctx, ensure_ascii=False, separators=(",", ":"))[:12000]
    except Exception:
        return str(ctx)[:5000]


def _format_today_schedule(ctx: Dict[str, Any]) -> str:
    first = ctx.get("primeiro_nome") or ctx.get("nome") or "Professor"
    hoje = ctx.get("hoje") if isinstance(ctx.get("hoje"), dict) else {}
    aulas = hoje.get("aulas") or []
    if not aulas:
        return f"{first}, não encontrei aulas na sua agenda de hoje."
    lines = [f"{first}, suas aulas de hoje são:", ""]
    for aula in aulas:
        hora = aula.get("hora") or "--:--"
        curso = aula.get("curso") or "Aula"
        alunos = aula.get("alunos") or []
        lines.append(f"*{hora}* — {curso}")
        for aluno in alunos:
            lines.append(f"• {aluno}")
        lines.append("")
    total = hoje.get("total_aulas") or len(aulas)
    lines.append(f"Você tem *{total} aulas* hoje.")
    return "\n".join(lines).strip()


def _format_today_counts(ctx: Dict[str, Any]) -> str:
    first = ctx.get("primeiro_nome") or ctx.get("nome") or "Professor"
    hoje = ctx.get("hoje") if isinstance(ctx.get("hoje"), dict) else {}
    aulas = hoje.get("aulas") or []
    total_aulas = hoje.get("total_aulas") or len(aulas)
    atendimentos = sum(len(a.get("alunos") or []) for a in aulas)
    unicos = []
    seen = set()
    for aula in aulas:
        for aluno in aula.get("alunos") or []:
            key = _norm_text(aluno)
            if key and key not in seen:
                seen.add(key)
                unicos.append(aluno)
    if not aulas:
        return f"{first}, não encontrei aulas na sua agenda de hoje."
    if atendimentos == len(unicos):
        return f"{first}, hoje você tem *{len(unicos)} alunos* na agenda, em *{total_aulas} aulas*."
    return f"{first}, hoje você tem *{atendimentos} atendimentos de alunos* em *{total_aulas} aulas*. Contando alunos únicos, são *{len(unicos)} alunos diferentes*."


def _aula_minutes(hora: str) -> Optional[int]:
    m = re.match(r"^(\d{1,2}):(\d{2})", str(hora or ""))
    if not m:
        return None
    return int(m.group(1)) * 60 + int(m.group(2))


def _today_agenda_stats(ctx: Dict[str, Any]) -> Dict[str, Any]:
    hoje = ctx.get("hoje") if isinstance(ctx.get("hoje"), dict) else {}
    aulas = hoje.get("aulas") or []
    total_aulas = hoje.get("total_aulas") or len(aulas)
    atendimentos = sum(len(a.get("alunos") or []) for a in aulas)
    chamadas_feitas = sum(1 for a in aulas if a.get("chamada_feita") is True)
    first_min = None
    last_min = None
    for aula in aulas:
        mins = _aula_minutes(aula.get("hora"))
        if mins is None:
            continue
        first_min = mins if first_min is None else min(first_min, mins)
        last_min = mins if last_min is None else max(last_min, mins)
    now = datetime.now(ZoneInfo("America/Sao_Paulo"))
    now_min = now.hour * 60 + now.minute
    phase = "sem_agenda"
    if aulas:
        if first_min is not None and now_min < first_min - 45:
            phase = "antes"
        elif last_min is not None and now_min >= last_min + 50:
            phase = "depois"
        else:
            phase = "durante"
    return {
        "aulas": aulas,
        "total_aulas": total_aulas,
        "atendimentos": atendimentos,
        "chamadas_feitas": chamadas_feitas,
        "phase": phase,
        "now_min": now_min,
    }


def _short_student_hint(aulas: list[Dict[str, Any]]) -> str:
    names = []
    for aula in aulas:
        for aluno in aula.get("alunos") or []:
            first = str(aluno).split()[0] if aluno else ""
            if first and first not in names:
                names.append(first)
            if len(names) >= 3:
                break
        if len(names) >= 3:
            break
    if not names:
        return "algum aluno específico"
    if len(names) == 1:
        return names[0]
    return ", ".join(names[:-1]) + " ou " + names[-1]


def _format_contextual_checkin(ctx: Dict[str, Any]) -> str:
    first = ctx.get("primeiro_nome") or ctx.get("nome") or "Professor"
    s = _today_agenda_stats(ctx)
    aulas = s["aulas"]
    if not aulas:
        return f"E aí, {first}! Tô por aqui. Hoje não achei aula na tua agenda — quer olhar algum aluno ou registro comigo?"
    hint = _short_student_hint(aulas)
    if s["phase"] == "depois":
        return (
            f"E aí, {first}! Vi que teu dia fechou com *{s['total_aulas']} aulas* e *{s['atendimentos']} atendimentos*.\n\n"
            f"Como foram as aulas hoje? Curtiu o fluxo? Se quiser, me fala rapidinho como foi com {hint} que eu já te ajudo a transformar isso em registro ou próximo passo."
        )
    if s["phase"] == "durante":
        return (
            f"E aí, {first}! Tô contigo. Teu dia tá com *{s['total_aulas']} aulas* na agenda.\n\n"
            f"Se quiser, me manda qual aluno tá na mão agora que eu entro direto na preparação ou no registro."
        )
    return (
        f"Bom dia, {first}! Hoje você tem *{s['total_aulas']} aulas* e *{s['atendimentos']} atendimentos*.\n\n"
        f"Quer que eu te ajude a preparar a primeira ou já olhar algum aluno específico?"
    )


def _format_day_reflection(ctx: Dict[str, Any]) -> str:
    first = ctx.get("primeiro_nome") or ctx.get("nome") or "Professor"
    s = _today_agenda_stats(ctx)
    aulas = s["aulas"]
    if not aulas:
        return f"{first}, não achei aulas na tua agenda de hoje. Se você me disser o aluno ou turma, eu olho por outro caminho."
    hint = _short_student_hint(aulas)
    chamadas = s.get("chamadas_feitas") or 0
    return (
        f"Pelo sistema, teu dia teve *{s['total_aulas']} aulas* e *{s['atendimentos']} atendimentos*. "
        f"Eu vi chamada marcada em *{chamadas}/{s['total_aulas']}* aulas.\n\n"
        f"Mas o mais importante eu ainda preciso de você: como foi na prática? Rolou algo bom, difícil ou diferente com {hint}? Me manda em áudio ou texto que eu organizo em registro pedagógico e próximo passo."
    )


def _is_day_reflection_question(norm: str) -> bool:
    return any(p in norm for p in [
        "como foram minhas aulas", "como foram as aulas", "como foi minhas aulas",
        "como foi as aulas", "como foram hoje", "como foi hoje"
    ])


def _is_light_checkin(norm: str) -> bool:
    clean = re.sub(r"[^a-z0-9áéíóúâêôãõç\s]", " ", norm)
    clean = re.sub(r"\s+", " ", clean).strip()
    if not clean:
        return False
    tokens = clean.split()
    if len(tokens) > 8:
        return False
    allowed = {
        "oi", "ola", "olá", "opa", "fala", "coe", "coé", "salve", "qual", "é", "e", "ai", "aí",
        "bom", "boa", "dia", "tarde", "noite", "fabio", "fábio", "ta", "tá", "por",
        "aqui", "comigo", "tudo", "bem", "td", "blz", "beleza", "mano", "cara",
    }
    signal = {"oi", "ola", "olá", "opa", "fala", "coe", "coé", "salve", "qual", "fabio", "fábio", "tá", "ta", "bom", "boa"}
    return all(t in allowed for t in tokens) and any(t in signal for t in tokens)



def _admin_deep_analysis_intent(row: Dict[str, Any]) -> bool:
    """Detect heavy admin analysis that should become async fan-out."""
    if (row.get("identidade_tipo") or "professor") != "admin":
        return False
    text = _norm_text(row.get("content") or row.get("media_extracted_text") or "")
    if not text:
        return False
    triggers = [
        "pente fino", "pente-fino", "faz o pente", "fazer o pente",
        "merece atencao", "merecem atencao", "precisa de atencao", "pedem atencao",
        "quem olhar primeiro", "casos que pedem", "lista curta", "sem achismo",
    ]
    return any(t in text for t in triggers)


def _unit_from_text_and_history(row: Dict[str, Any]) -> Dict[str, Any]:
    hist = recent_history_for_row(row, 8)
    hay = _norm_text("\n".join([(h.get("content") or "") for h in hist] + [row.get("content") or ""]))
    units = sb_get("/rest/v1/unidades", {"select": "id,nome,codigo", "order": "nome.asc"})
    wanted = None
    if "campo grande" in hay or re.search(r"\bcg\b", hay):
        wanted = "campo grande"
    elif "recreio" in hay or re.search(r"\brec\b", hay):
        wanted = "recreio"
    elif "barra" in hay:
        wanted = "barra"
    for u in units or []:
        if wanted and _norm_text(u.get("nome")) == wanted:
            return u
    for u in units or []:
        if _norm_text(u.get("nome")) == "campo grande":
            return u
    return (units or [{}])[0]


def _num(value: Any, default: float = 0.0) -> float:
    try:
        if value is None or value == "":
            return default
        return float(value)
    except Exception:
        return default


def _int(value: Any, default: int = 0) -> int:
    try:
        if value is None or value == "":
            return default
        return int(float(value))
    except Exception:
        return default


def _fetch_async_roster(unit: Dict[str, Any]) -> Dict[str, Any]:
    rows = sb_get("/rest/v1/vw_professores_carteira_resumo", {
        "select": "professor_id,professor_nome,total_alunos,alunos_verdes,alunos_amarelos,alunos_vermelhos,alunos_sem_avaliacao",
        "unidade_id": f"eq.{unit.get('id')}",
        "order": "total_alunos.desc.nullslast",
        "limit": "200",
    })
    return {"collector": "carteira", "rows": rows or []}


def _fetch_async_registros(unit: Dict[str, Any]) -> Dict[str, Any]:
    mes_atual = datetime.now(ZoneInfo("America/Sao_Paulo")).date().replace(day=1).isoformat()
    rows = sb_get("/rest/v1/vw_aderencia_registro_professor", {
        "select": "professor_id,professor_nome,mes,aulas,com_registro,pct_cobertura,registros_fabio,registros_emusys,aulas_cobraveis,pct_north_star,horas_medianas_ate_registrar",
        "unidade_id": f"eq.{unit.get('id')}",
        "mes": f"eq.{mes_atual}",
        "order": "pct_cobertura.asc",
        "limit": "120",
    })
    latest = {}
    for r in rows or []:
        pid = r.get("professor_id")
        if pid and pid not in latest:
            latest[pid] = r
    return {"collector": "registros", "rows": list(latest.values())}


def _fetch_async_jornada(unit: Dict[str, Any]) -> Dict[str, Any]:
    rows = sb_get("/rest/v1/vw_jornada_professor_atual", {
        "select": "professor_id,professor_nome,aluno_id,aluno_nome,curso_nome,presencas,faltas,nr_aulas_passadas,percentual_presenca_contrato,percentual_jornada,ultima_aula_registrada",
        "unidade_id": f"eq.{unit.get('id')}",
        "order": "professor_nome.asc,aluno_nome.asc",
        "limit": "2500",
    })
    return {"collector": "jornada", "rows": rows or []}


def _fetch_async_retencao(unit: Dict[str, Any]) -> Dict[str, Any]:
    nome = unit.get("nome") or ""
    ret = sb_get("/rest/v1/vw_ranking_professores_retencao", {
        "select": "unidade,professor,total_alunos,alunos_ativos,alunos_perdidos,tempo_medio_permanencia,presenca_media,ticket_medio",
        "unidade": f"eq.{nome}",
        "order": "alunos_perdidos.desc.nullslast",
        "limit": "200",
    })
    evas = sb_get("/rest/v1/vw_ranking_professores_evasoes", {
        "select": "professor,unidade,ano,evasoes,matriculas,taxa_conversao,renovacoes,taxa_renovacao,nivel_risco",
        "unidade": f"eq.{nome}",
        "order": "ano.desc,evasoes.desc.nullslast",
        "limit": "200",
    })
    return {"collector": "retencao_evasoes", "retencao": ret or [], "evasoes": evas or []}


def collect_admin_deep_analysis(row: Dict[str, Any]) -> Dict[str, Any]:
    """Fan-out read-only collectors for heavy admin/professor analysis."""
    unit = _unit_from_text_and_history(row)
    started = time.monotonic()
    collectors = {
        "carteira": _fetch_async_roster,
        "registros": _fetch_async_registros,
        "jornada": _fetch_async_jornada,
        "retencao_evasoes": _fetch_async_retencao,
    }
    results: Dict[str, Any] = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=4) as ex:
        futs = {ex.submit(fn, unit): name for name, fn in collectors.items()}
        for fut in concurrent.futures.as_completed(futs, timeout=90):
            name = futs[fut]
            try:
                results[name] = fut.result()
            except Exception as e:
                results[name] = {"collector": name, "error": str(e)[:500]}
    evidence = _score_admin_deep_analysis(unit, results)
    evidence["elapsed_collect_s"] = round(time.monotonic() - started, 2)
    return evidence


def _score_admin_deep_analysis(unit: Dict[str, Any], results: Dict[str, Any]) -> Dict[str, Any]:
    professors: Dict[str, Dict[str, Any]] = {}

    def get_prof(pid: Any, name: Any = None) -> Dict[str, Any]:
        key = str(pid or _norm_text(name))
        if key not in professors:
            professors[key] = {"professor_id": pid, "professor_nome": name, "score": 0, "motivos": [], "evidencias": {}}
        if name and not professors[key].get("professor_nome"):
            professors[key]["professor_nome"] = name
        return professors[key]

    for r in (results.get("carteira") or {}).get("rows") or []:
        p = get_prof(r.get("professor_id"), r.get("professor_nome"))
        total = _int(r.get("total_alunos"))
        verm = _int(r.get("alunos_vermelhos"))
        amar = _int(r.get("alunos_amarelos"))
        sem = _int(r.get("alunos_sem_avaliacao"))
        p["evidencias"]["carteira"] = {"total_alunos": total, "vermelhos": verm, "amarelos": amar, "sem_avaliacao": sem}
        if verm:
            p["score"] += verm * 6
            p["motivos"].append(f"{verm} aluno(s) em vermelho")
        if amar:
            p["score"] += amar * 3
            p["motivos"].append(f"{amar} aluno(s) em amarelo")
        if sem >= 3:
            p["score"] += min(sem, 10)
            p["motivos"].append(f"{sem} aluno(s) sem avaliação")

    for r in (results.get("registros") or {}).get("rows") or []:
        p = get_prof(r.get("professor_id"), r.get("professor_nome"))
        aulas = _int(r.get("aulas"))
        cobertura = _num(r.get("pct_cobertura"))
        north = _num(r.get("pct_north_star"))
        cobraveis = _int(r.get("aulas_cobraveis"))
        p["evidencias"]["registros"] = {"mes": r.get("mes"), "aulas": aulas, "com_registro": _int(r.get("com_registro")), "pct_cobertura": cobertura, "pct_north_star": north, "aulas_cobraveis": cobraveis}
        if aulas >= 10 and cobertura < 30:
            p["score"] += 8
            p["motivos"].append(f"baixa cobertura de registros ({cobertura:.0f}% em {aulas} aulas no mês)")
        elif aulas >= 10 and cobertura < 60:
            p["score"] += 4
            p["motivos"].append(f"cobertura de registros intermediária ({cobertura:.0f}%)")
        if cobraveis > 0:
            p["score"] += min(cobraveis, 12)
            p["motivos"].append(f"{cobraveis} aula(s) cobráveis sem registro")

    jornada_by_prof: Dict[Any, list[Dict[str, Any]]] = {}
    for r in (results.get("jornada") or {}).get("rows") or []:
        pid = r.get("professor_id")
        jornada_by_prof.setdefault(pid, []).append(r)
        get_prof(pid, r.get("professor_nome"))
    for pid, rows in jornada_by_prof.items():
        p = get_prof(pid, rows[0].get("professor_nome") if rows else None)
        low = []
        faltas3 = []
        final_journey = []
        for r in rows:
            pct = _num(r.get("percentual_presenca_contrato"), 100)
            faltas = _int(r.get("faltas"))
            jornada = _num(r.get("percentual_jornada"))
            passadas = _int(r.get("nr_aulas_passadas"))
            if passadas >= 4 and pct < 80:
                low.append(r)
            if faltas >= 3:
                faltas3.append(r)
            if jornada >= 80 and pct < 85:
                final_journey.append(r)
        p["evidencias"]["jornada"] = {"alunos_analisados": len(rows), "presenca_baixa": len(low), "faltas_3mais": len(faltas3), "fim_jornada_com_risco": len(final_journey)}
        if low:
            p["score"] += min(len(low) * 3, 18)
            p["motivos"].append(f"{len(low)} aluno(s) com presença abaixo de 80%")
        if faltas3:
            p["score"] += min(len(faltas3) * 2, 12)
            p["motivos"].append(f"{len(faltas3)} aluno(s) com 3+ faltas")
        if final_journey:
            p["score"] += min(len(final_journey) * 3, 12)
            p["motivos"].append(f"{len(final_journey)} aluno(s) no fim da jornada com risco")

    by_name = {_norm_text(p.get("professor_nome")): p for p in professors.values() if p.get("professor_nome")}
    latest_evas_by_name = {}
    for r in (results.get("retencao_evasoes") or {}).get("evasoes") or []:
        name = _norm_text(r.get("professor"))
        if name and name not in latest_evas_by_name:
            latest_evas_by_name[name] = r
    for name, r in latest_evas_by_name.items():
        p = by_name.get(name)
        if not p:
            continue
        evas = _int(r.get("evasoes"))
        risco = str(r.get("nivel_risco") or "")
        p["evidencias"]["evasoes"] = {"ano": r.get("ano"), "evasoes": evas, "nivel_risco": risco, "taxa_renovacao": r.get("taxa_renovacao")}
        if evas > 0:
            p["score"] += min(evas * 3, 15)
            p["motivos"].append(f"{evas} evasão(ões) no recorte do ranking")
        if "alto" in _norm_text(risco):
            p["score"] += 5
            p["motivos"].append("nível de risco alto no ranking")

    ranked = [p for p in professors.values() if p.get("score", 0) > 0]
    ranked.sort(key=lambda x: (x.get("score", 0), _int((x.get("evidencias") or {}).get("carteira", {}).get("total_alunos"))), reverse=True)
    return {
        "unidade": {"id": unit.get("id"), "nome": unit.get("nome"), "codigo": unit.get("codigo")},
        "professores_analisados": len(professors),
        "top": ranked[:8],
        "collectors_ok": {k: not bool((v or {}).get("error")) for k, v in results.items()},
    }


def _fallback_admin_analysis_text(evidence: Dict[str, Any]) -> str:
    unit = (evidence.get("unidade") or {}).get("nome") or "a unidade"
    top = evidence.get("top") or []
    if not top:
        return f"Alf, fiz o pente-fino em {unit} e não apareceu nenhum alerta forte com os dados disponíveis. Eu olharia mais por rotina de coordenação do que por risco objetivo agora."
    lines = [f"Fechei o pente-fino de {unit}, Alf. Sem caça às bruxas: isso aqui é prioridade de apoio, não sentença.", ""]
    for i, p in enumerate(top[:5], 1):
        nome = p.get("professor_nome") or "Professor"
        motivos = p.get("motivos") or []
        ev = p.get("evidencias") or {}
        carteira = ev.get("carteira") or {}
        resumo = "; ".join(motivos[:3]) or "sinal misto nos indicadores"
        alunos = carteira.get("total_alunos")
        sufixo = f" — carteira: {alunos} aluno(s)" if alunos is not None else ""
        lines.append(f"{i}. *{nome}*{sufixo}. Motivo: {resumo}.")
    lines += ["", "Eu começaria pelos 3 primeiros com conversa de apoio e evidência na mão: presença, registro e aluno em risco. Não entraria como cobrança seca."]
    return "\n".join(lines)[:3900]


def _hermes_admin_analysis_text(row: Dict[str, Any], evidence: Dict[str, Any]) -> str:
    prompt = f"""Você é o Fábio, agente pedagógico da LA Music, falando com o Alf no WhatsApp.
O bridge já rodou consultores paralelos read-only e trouxe evidências. Escreva a resposta final curta, humana e útil.
Tom: parceiro de gestão, sem relatório seco, sem caça às bruxas. Priorize apoio pedagógico.
Não invente dados fora do JSON. Se um indicador é limitação, diga como cautela.

PEDIDO ORIGINAL:
{row.get('content') or ''}

EVIDÊNCIAS_JSON:
{json.dumps(evidence, ensure_ascii=False, separators=(',', ':'))[:22000]}

Formato desejado:
- abrir com conclusão direta;
- listar no máximo 5 professores prioritários com motivo/evidência;
- fechar com próximo passo sugerido.
Responda apenas a mensagem final."""
    try:
        return run_hermes_api(prompt, professor_id=0, channel=row.get("channel") or "whatsapp")
    except Exception as e:
        log("async_admin_analysis_hermes_failed", id=row.get("id"), error=str(e)[-800:])
        return _fallback_admin_analysis_text(evidence)


def _send_row_whatsapp(row: Dict[str, Any], text: str) -> None:
    if (row.get("identidade_tipo") or "professor") == "admin":
        phone = admin_phone(int(row["usuario_id"]))
    else:
        phone = professor_phone(int(row["professor_id"]))
    if not phone:
        raise RuntimeError("whatsapp_phone_missing")
    r = requests.post(
        f"{UAZAPI_URL}/send/text",
        headers={"Content-Type": "application/json", "token": UAZAPI_TOKEN},
        json=whatsapp_send_payload(phone, text),
        timeout=_HTTP_TIMEOUT,
    )
    if r.status_code >= 400:
        raise RuntimeError(f"uazapi send/text async {r.status_code}: {r.text[:500]}")
    log("whatsapp_sent", usuario_id=row.get("usuario_id"), professor_id=row.get("professor_id"), phone_tail=phone[-4:], async_job=True)


def _run_async_admin_analysis(row: Dict[str, Any]) -> None:
    try:
        log("async_admin_analysis_started", id=row.get("id"), usuario_id=row.get("usuario_id"), channel=row.get("channel"))
        evidence = collect_admin_deep_analysis(row)
        answer = _hermes_admin_analysis_text(row, evidence)
        insert_fabio_response_for_row(row, answer, row.get("channel") or "app")
        if row.get("channel") == "whatsapp":
            _send_row_whatsapp(row, answer)
        log("async_admin_analysis_done", id=row.get("id"), elapsed_collect_s=evidence.get("elapsed_collect_s"), top_count=len(evidence.get("top") or []))
    except Exception as e:
        log("async_admin_analysis_failed", id=row.get("id"), error=str(e)[-1000:])
        try:
            fail = "Alf, tentei rodar o pente-fino agora mas bati num erro técnico na coleta. Já deixei logado aqui pra corrigir sem perder o fio."
            insert_fabio_response_for_row(row, fail, row.get("channel") or "app")
            if row.get("channel") == "whatsapp":
                _send_row_whatsapp(row, fail)
        except Exception:
            pass


def start_async_admin_analysis(row: Dict[str, Any]) -> None:
    t = threading.Thread(target=_run_async_admin_analysis, args=(dict(row),), daemon=True)
    t.start()

def try_fast_response(row: Dict[str, Any]) -> Optional[str]:
    """Return a deterministic quick answer for safe/simple intents.

    This intentionally covers only low-risk operational questions. Anything
    pedagogical, ambiguous, creative, or requiring reasoning falls back to Hermes.
    """
    text = row.get("content") or row.get("media_extracted_text") or ""
    norm = _norm_text(text)
    if not norm:
        return None
    # Never fast-path pedagogical history/material/preparation requests.
    if _has_pedagogical_history_intent(text, []):
        return None
    blocked = ["prepara", "preparar", "material", "backing", "playback", "suno", "registro", "registrar", "prontuario", "conteudo", "ultima aula", "aluno "]
    if any(b in norm for b in blocked):
        return None

    professor_id = int(row["professor_id"])
    ctx = professor_context(professor_id)
    if not isinstance(ctx, dict) or not ctx.get("ok"):
        return None
    first = ctx.get("primeiro_nome") or ctx.get("nome") or "Professor"

    # Conversational check-ins/reflections must go through Hermes/GPT.
    # The bridge should not write the professor-facing prose for these.
    if _is_day_reflection_question(norm) or _is_light_checkin(norm):
        return None

    asks_today = "hoje" in norm or "hj" in norm or "minhas aulas" in norm or "minha agenda" in norm
    asks_schedule = any(p in norm for p in ["quais minhas aulas", "minhas aulas", "minha agenda", "aulas de hoje", "agenda de hoje", "horarios de hoje", "horários de hoje"])
    asks_count = any(p in norm for p in ["quantos alunos", "quantas aulas", "qtd alunos", "qtd de alunos", "total de alunos"])
    if asks_count and asks_today:
        return _format_today_counts(ctx)
    if asks_schedule and asks_today:
        return _format_today_schedule(ctx)
    return None


def generate_answer(row: Dict[str, Any]) -> tuple[str, str]:
    if (row.get("identidade_tipo") or "professor") == "professor":
        fast = try_fast_response(row)
        if fast:
            return fast, "fast_path"

    prompt = build_prompt(row)
    professor_id = int(row.get("professor_id") or 0)
    usuario_id = row.get("usuario_id")
    channel = row.get("channel") or "app"
    if HERMES_MODE in {"api", "api_fallback", "api-first"}:
        try:
            return run_hermes_api(prompt, professor_id=professor_id, channel=channel), "hermes_api"
        except Exception as e:
            log("hermes_api_failed", professor_id=professor_id, usuario_id=usuario_id, identidade_tipo=row.get("identidade_tipo"), channel=channel, error=str(e)[-800:])
            if not HERMES_API_FALLBACK_ONESHOT:
                raise
            return run_hermes_oneshot(prompt), "hermes_api_fallback_oneshot"

    return run_hermes_oneshot(prompt), "hermes"


def build_prompt(row: Dict[str, Any]) -> str:
    tipo = row.get("identidade_tipo") or "professor"
    hist = recent_history_for_row(row, 12)
    text = row.get("content") or row.get("media_extracted_text") or ""
    hora_local_sp = datetime.now(ZoneInfo("America/Sao_Paulo")).strftime("%Y-%m-%d %H:%M")
    lines = []
    for h in hist:
        content = (h.get("content") or "").strip()
        if content:
            lines.append(f"{h.get('role')}: {content[:1200]}")
    if tipo == "admin":
        usuario_id = int(row["usuario_id"])
        contexto_professor = admin_context(usuario_id)
        contexto_pedagogico = None
        agenda_stats = {}
        identidade_linha = f"- identidade_tipo: admin\n- usuario_id: {usuario_id}\n- modo: gestão/admin do Alf; visão ampla, não limitada a professor comum"
    else:
        professor_id = int(row["professor_id"])
        contexto_professor = professor_context(professor_id)
        contexto_pedagogico = pedagogical_prefetch(professor_id, text, hist)
        agenda_stats = _today_agenda_stats(contexto_professor) if isinstance(contexto_professor, dict) and contexto_professor.get("ok") else {}
        identidade_linha = f"- identidade_tipo: professor\n- professor_id: {professor_id}"
    return f"""Canal: chat livre do Fábio com professor/admin da LA Music.
Use a skill chat-fabio-la-music como guia principal de personalidade, roteamento e guardrails.
Para presença pendente/governança de presença, siga governanca-presenca-fabio-la-music: preview-first, read-only, liderar pelo conteúdo, sem cobrança policial e sem auto-envio/escala sem validação.
Responda somente a mensagem final que será enviada ao usuário; não mencione detalhes técnicos.

IDENTIDADE E CONTEXTO JÁ RESOLVIDOS PELO BRIDGE:
{identidade_linha}
- contexto_json: {compact_professor_context(contexto_professor)}
- hora_local_sao_paulo: {hora_local_sp}
- agenda_stats_json: {json.dumps(agenda_stats, ensure_ascii=False, separators=(",", ":"))[:4000]}

CONTEXTO DE CONVERSA / TOM:
- Para cumprimentos/check-ins curtos (ex: "qual é Fábio", "coe Fábio", "tá aí?"), não responda com menu fixo. Use hora local, fase do dia e agenda para soar presente.
- Se for fim do dia ou depois das aulas, puxe fechamento natural: pergunte como foram as aulas, se rolou algo bom/difícil/diferente, e ofereça organizar em registro/próximo passo.
- Não cobre pendência/chamada/registro em tom fiscalizador nesse chat livre, a menos que o professor peça explicitamente ou a mensagem seja de um fluxo de cobrança.
- Se mencionar dados do sistema, deixe claro quando é dado operacional e quando precisa do relato humano do professor.

CONTEXTO PEDAGÓGICO PRÉ-BUSCADO QUANDO A INTENÇÃO PEDE HISTÓRICO/ÚLTIMA AULA:
{compact_pedagogical_context(contexto_pedagogico)}

Regras obrigatórias para esta conversa 1:1:
- O usuário já está identificado acima. Nunca peça nome completo, unidade ou confirmação de identidade se o contexto_json ok=true.
- Se identidade_tipo=admin, você está falando com o Alf em modo gestão/admin: visão ampla, parceria e conversa de bastidor, sem fingir que ele é professor comum.
- Com o Alf, preserve o jeito vivo que vinha funcionando: parceiro, natural, caloroso, com leveza quando couber. Não vire relatório seco só porque a pergunta tem dado operacional.
- Se a pergunta admin for objetiva e o dado já estiver no contexto_json (ex.: visao_geral.professores_por_unidade), use esse dado diretamente para não demorar recalculando; mas não responda como relatório seco. Faça uma resposta curta com encaixe humano no tom da conversa recente (ex.: “Boa, Alf…”, “Mano…”, “Sim…”), sem forçar gíria se não couber.
- Se identidade_tipo=professor e perguntarem agenda de hoje, alunos de hoje, carteira, unidade ou pendências, use o contexto_json antes de perguntar qualquer coisa.
- Se identidade_tipo=professor e perguntarem conteúdo da última aula, continuidade, prontuário ou “pra relembrar”, use o CONTEXTO PEDAGÓGICO PRÉ-BUSCADO.
- Se a última aula cronológica estiver sem registro, mas existir ultimo_registro_com_conteudo mais antigo, diga as duas coisas: “a última aula em DATA está sem registro; o último conteúdo registrado que encontrei foi em DATA...”. Nunca diga apenas que não tem conteúdo quando houver registro anterior.
- Se o contexto_json vier ok=false ou incompleto, explique a limitação de forma curta e peça só a informação mínima.

Contexto da conversa recente:
{chr(10).join(lines) if lines else '(sem histórico recente)'}

Mensagem atual do usuário:
{text}

Responda apenas a mensagem final que será enviada ao usuário."""


def run_hermes_api(prompt: str, professor_id: Optional[int] = None, channel: Optional[str] = None) -> str:
    if not HERMES_API_KEY:
        raise RuntimeError("FABIO_HERMES_API_KEY/API_SERVER_KEY missing")
    headers = {
        "Authorization": f"Bearer {HERMES_API_KEY}",
        "Content-Type": "application/json",
    }
    body = {
        "model": HERMES_API_MODEL,
        "messages": [{"role": "user", "content": prompt}],
        "stream": False,
    }
    t0 = time.monotonic()
    r = requests.post(HERMES_API_URL, headers=headers, json=body, timeout=HERMES_API_TIMEOUT)
    dt = round(time.monotonic() - t0, 2)
    if r.status_code >= 400:
        raise RuntimeError(f"hermes api http={r.status_code} elapsed={dt}s: {r.text[:800]}")
    data = r.json()
    out = (((data.get("choices") or [{}])[0].get("message") or {}).get("content") or "").strip()
    if not out:
        raise RuntimeError(f"hermes api returned empty response elapsed={dt}s")
    log("hermes_api_ok", professor_id=professor_id, channel=channel, elapsed_s=dt, model=HERMES_API_MODEL)
    return out[-4000:]


def run_hermes_oneshot(prompt: str) -> str:
    cmd = HERMES_CMD.split() + ["--accept-hooks"]
    if CHAT_SKILLS:
        cmd += ["--skills", CHAT_SKILLS]
    cmd += ["--oneshot", prompt]
    env = os.environ.copy()
    env.setdefault("HERMES_HOME", str(HERMES_HOME))
    env.setdefault("HOME", str(ROOT_DIR))
    proc = subprocess.run(
        cmd,
        cwd=str(ROOT_DIR),
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        timeout=int(os.getenv("FABIO_CHAT_HERMES_TIMEOUT", "180")),
    )
    if proc.returncode != 0:
        raise RuntimeError(f"hermes oneshot rc={proc.returncode}: {proc.stderr[-1000:]}")
    out = proc.stdout.strip()
    if not out:
        raise RuntimeError("hermes oneshot returned empty response")
    return out[-4000:]


def whatsapp_send_payload(number: str, text: str) -> Dict[str, Any]:
    """Build UAZAPI send/text payload with typing indicator delay.

    UAZAPI `delay` is milliseconds and shows "Digitando..." during the wait.
    Keep it short: this is UX polish, not artificial waiting.
    """
    base_delay = int(os.getenv("FABIO_WHATSAPP_TYPING_DELAY_MS", "0"))
    max_delay = int(os.getenv("FABIO_WHATSAPP_TYPING_DELAY_MAX_MS", "1000"))
    per_char = int(os.getenv("FABIO_WHATSAPP_TYPING_DELAY_PER_CHAR_MS", "0"))
    delay = base_delay
    if per_char > 0:
        delay = max(delay, len(text or "") * per_char)
    delay = max(0, min(delay, max_delay))
    payload = {"number": number, "text": text, "readchat": True}
    if delay > 0:
        payload["delay"] = int(delay)
    return payload

def whatsapp_target_phone_for_row(row: Dict[str, Any]) -> Optional[str]:
    if (row.get("identidade_tipo") or "professor") == "admin":
        return admin_phone(int(row["usuario_id"]))
    return professor_phone(int(row["professor_id"]))


def send_whatsapp_presence(phone: str, presence: str = "composing", delay_ms: Optional[int] = None) -> None:
    """Show WhatsApp presence while Hermes is generating.

    UAZAPI /message/presence is async, refreshes every 10s, and is cancelled
    automatically when /send/text sends the final message to the same chat.
    """
    if not UAZAPI_TOKEN:
        return
    if delay_ms is None:
        delay_ms = int(os.getenv("FABIO_WHATSAPP_PRESENCE_DELAY_MS", "300000"))
    delay_ms = max(0, min(int(delay_ms), 300000))
    payload = {"number": phone, "presence": presence}
    if delay_ms > 0 and presence != "paused":
        payload["delay"] = delay_ms
    r = requests.post(
        f"{UAZAPI_URL}/message/presence",
        headers={"Content-Type": "application/json", "token": UAZAPI_TOKEN},
        json=payload,
        timeout=_HTTP_TIMEOUT,
    )
    if r.status_code >= 400:
        raise RuntimeError(f"uazapi message/presence {r.status_code}: {r.text[:500]}")
    log("whatsapp_presence_sent", presence=presence, phone_tail=phone[-4:], delay_ms=delay_ms)


def send_whatsapp_presence_for_row(row: Dict[str, Any], presence: str = "composing") -> None:
    phone = whatsapp_target_phone_for_row(row)
    if not phone:
        log("whatsapp_presence_phone_missing", identidade_tipo=row.get("identidade_tipo"), professor_id=row.get("professor_id"), usuario_id=row.get("usuario_id"))
        return
    send_whatsapp_presence(phone, presence=presence)

def send_whatsapp_text(professor_id: int, text: str) -> None:
    if not UAZAPI_TOKEN:
        log("uazapi_token_missing_skip_send", professor_id=professor_id)
        return
    phone = professor_phone(professor_id)
    if not phone:
        log("professor_phone_missing_skip_send", professor_id=professor_id)
        return
    r = requests.post(
        f"{UAZAPI_URL}/send/text",
        headers={"Content-Type": "application/json", "token": UAZAPI_TOKEN},
        json=whatsapp_send_payload(phone, text),
        timeout=_HTTP_TIMEOUT,
    )
    if r.status_code >= 400:
        raise RuntimeError(f"uazapi send/text {r.status_code}: {r.text[:500]}")
    log("whatsapp_sent", professor_id=professor_id, phone_tail=phone[-4:], typing_delay_ms=whatsapp_send_payload(phone, text).get("delay", 0))


def process_one() -> bool:
    first_row = claim_next_message()
    if not first_row:
        return False
    log("processing_message", id=first_row.get("id"), professor_id=first_row.get("professor_id"), usuario_id=first_row.get("usuario_id"), identidade_tipo=first_row.get("identidade_tipo"), channel=first_row.get("channel"))
    if first_row.get("channel") == "whatsapp":
        try:
            send_whatsapp_presence_for_row(first_row, "composing")
        except Exception as e:
            log("whatsapp_presence_failed", id=first_row.get("id"), error=str(e)[:500])
    batch = collect_message_batch(first_row)
    row = merge_message_batch(batch)
    if _admin_deep_analysis_intent(row):
        answer = "Fechado, Alf. Vou rodar esse pente-fino em paralelo agora — carteira, presença/jornada, registros e retenção — e já te devolvo uma lista curta com evidência, sem achismo."
        insert_fabio_response_for_row(row, answer, row.get("channel") or "app")
        if row.get("channel") == "whatsapp":
            try:
                _send_row_whatsapp(row, answer)
            except Exception as e:
                log("whatsapp_send_failed", id=first_row.get("id"), error=str(e)[:500])
        for mid in row.get("_batch_ids") or [str(first_row["id"])]:
            mark_done(str(mid))
        start_async_admin_analysis(row)
        log("processed_message_async_admin_analysis", id=first_row.get("id"), batch_count=row.get("_batch_count", 1))
        return True

    try:
        answer, answer_source = generate_answer(row)
        log("answer_generated", id=first_row.get("id"), source=answer_source, batch_count=row.get("_batch_count", 1))
    except Exception as e:
        log("hermes_generation_failed", id=first_row.get("id"), error=str(e)[:500])
        answer = "Tive um erro ao processar sua mensagem agora. Pode me mandar de novo em instantes?"
    insert_fabio_response_for_row(row, answer, row.get("channel") or "app")
    if row.get("channel") == "whatsapp":
        try:
            if (row.get("identidade_tipo") or "professor") == "admin":
                phone = admin_phone(int(row["usuario_id"]))
                if not phone:
                    raise RuntimeError("admin_phone_missing")
                r = requests.post(
                    f"{UAZAPI_URL}/send/text",
                    headers={"Content-Type": "application/json", "token": UAZAPI_TOKEN},
                    json=whatsapp_send_payload(phone, answer),
                    timeout=_HTTP_TIMEOUT,
                )
                if r.status_code >= 400:
                    raise RuntimeError(f"uazapi send/text admin {r.status_code}: {r.text[:500]}")
                log("whatsapp_sent", usuario_id=row.get("usuario_id"), phone_tail=phone[-4:], typing_delay_ms=whatsapp_send_payload(phone, answer).get("delay", 0))
            else:
                send_whatsapp_text(int(row["professor_id"]), answer)
        except Exception as e:
            log("whatsapp_send_failed", id=first_row.get("id"), error=str(e)[:500])
    for mid in row.get("_batch_ids") or [str(first_row["id"])]:
        mark_done(str(mid))
    log("processed_message", id=first_row.get("id"), batch_count=row.get("_batch_count", 1))
    return True


class Handler(BaseHTTPRequestHandler):
    server_version = "FabioChatBridge/1.0"

    def _send(self, status: int, payload: Dict[str, Any]) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, fmt: str, *args: Any) -> None:
        log("http", remote=self.client_address[0], message=fmt % args)

    def do_GET(self) -> None:
        parsed = urlparse(self.path)
        if parsed.path == "/health":
            self._send(200, {"ok": True, "agent": "fabio-chat-bridge"})
        else:
            self._send(404, {"ok": False, "error": "not_found"})

    def do_POST(self) -> None:
        parsed = urlparse(self.path)
        expected = f"/webhook/uazapi/{BRIDGE_SECRET}"
        if not BRIDGE_SECRET or parsed.path != expected:
            self._send(404, {"ok": False, "error": "not_found"})
            return
        length = min(int(self.headers.get("Content-Length") or 0), 1024 * 1024)
        raw = self.rfile.read(length)
        try:
            body = json.loads(raw.decode("utf-8")) if raw else {}
        except Exception:
            self._send(400, {"ok": False, "error": "invalid_json"})
            return
        # Ack fast to avoid UAZAPI retries; process ingestion in this request (cheap).
        try:
            if is_ignorable_uazapi(body):
                self._send(200, {"ok": True, "status": "ignored"})
                return
            phone = extract_phone(body)
            text = extract_text(body)
            wa_id = extract_message_id(body)
            if not phone or not text:
                self._send(200, {"ok": True, "status": "ignored_missing_phone_or_text"})
                return
            identity = resolve_identity_by_phone(phone)
            inserted = insert_identity_message(identity, text, "whatsapp", wa_id)
            self._send(200, {"ok": True, "status": "queued", "duplicate": bool(inserted.get("duplicate")), "tipo": identity.get("tipo")})
            log("whatsapp_ingested", professor_id=identity.get("professor_id"), usuario_id=identity.get("usuario_id"), identidade_tipo=identity.get("tipo"), phone_tail=phone[-4:], duplicate=bool(inserted.get("duplicate")))
        except Exception as e:
            log("webhook_ingest_failed", error=str(e)[:500])
            self._send(200, {"ok": False, "status": "error"})


def serve() -> None:
    httpd = ThreadingHTTPServer(("0.0.0.0", PORT), Handler)
    log("http_listening", port=PORT)
    httpd.serve_forever()


def poll_loop(stop: threading.Event) -> None:
    log("poller_started", interval=POLL_INTERVAL)
    while not stop.is_set():
        try:
            did = process_one()
            if not did:
                stop.wait(POLL_INTERVAL)
        except Exception as e:
            log("poller_error", error=str(e)[:500])
            stop.wait(max(POLL_INTERVAL, 5))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--once", action="store_true", help="process one queued message and exit")
    parser.add_argument("--health", action="store_true")
    args = parser.parse_args()
    if args.health:
        print(json.dumps({"ok": bool(SUPABASE_KEY), "port": PORT, "uazapi_token": bool(UAZAPI_TOKEN), "secret": bool(BRIDGE_SECRET)}))
        return 0
    if args.once:
        return 0 if process_one() else 2
    stop = threading.Event()
    t = threading.Thread(target=poll_loop, args=(stop,), daemon=True)
    t.start()
    serve()
    return 0


_load_env_file()
# Refresh globals after .env load.
BRIDGE_SECRET = os.getenv("FABIO_CHAT_BRIDGE_SECRET", BRIDGE_SECRET)
PORT = int(os.getenv("FABIO_CHAT_BRIDGE_PORT", str(PORT)))
SUPABASE_URL = (os.getenv("LAREPORT_SUPABASE_URL") or SUPABASE_URL).rstrip("/")
SUPABASE_KEY = os.getenv("LAREPORT_SUPABASE_SERVICE_ROLE") or os.getenv("SUPABASE_SERVICE_ROLE_KEY") or SUPABASE_KEY
UAZAPI_URL = (os.getenv("FABIO_UAZAPI_URL") or os.getenv("UAZAPI_URL") or UAZAPI_URL).rstrip("/")
UAZAPI_TOKEN = os.getenv("FABIO_UAZAPI_TOKEN") or os.getenv("UAZAPI_TOKEN") or UAZAPI_TOKEN
# Os globais do Hermes tambem sao capturados no import, ANTES do _load_env_file
# acima -- entao sem esta linha run_hermes_api so funciona quando o systemd ja
# exportou a chave. Qualquer script que importe o bridge (ex.: o worker da
# devolutiva) tomava "FABIO_HERMES_API_KEY/API_SERVER_KEY missing".
HERMES_API_URL = (os.getenv("FABIO_HERMES_API_URL") or HERMES_API_URL).strip()
HERMES_API_KEY = (os.getenv("FABIO_HERMES_API_KEY") or os.getenv("API_SERVER_KEY") or HERMES_API_KEY or "").strip()
HERMES_API_MODEL = (os.getenv("FABIO_HERMES_API_MODEL") or HERMES_API_MODEL).strip()

if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        raise SystemExit(130)
